"""Initial migration from Peewee to SQLModel

Revision ID: 4e15a8bdbaf2
Revises:
Create Date: 2025-09-08 21:56:22.502367

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e15a8bdbaf2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "battlevideo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trainer_id", sa.Integer(), nullable=False),
        sa.Column("video_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("process_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "faintedlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("battle_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn", sa.Integer(), nullable=False),
        sa.Column(
            "your_pokemon_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "opponent_pokemon_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "fainted_pokemon_side", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "season",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("start_datetime", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("end_datetime", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_season_season"), "season", ["season"], unique=False)
    op.create_table(
        "trainer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trainer_identity"), "trainer", ["identity"], unique=False)
    op.create_table(
        "battle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("battle_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trainer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_battle_battle_id"), "battle", ["battle_id"], unique=True)
    op.create_table(
        "battlepokemonteam",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("battle_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pokemon_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["battle_id"],
            ["battle.battle_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "battlesummary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("battle_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("win_or_lose", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("next_rank", sa.Integer(), nullable=False),
        sa.Column("your_team", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("opponent_team", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("your_pokemon_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("your_pokemon_2", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("your_pokemon_3", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "opponent_pokemon_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "opponent_pokemon_2", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "opponent_pokemon_3", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("video", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("memo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["battle_id"],
            ["battle.battle_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inbattlepokemonlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("battle_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn", sa.Integer(), nullable=False),
        sa.Column("frame_number", sa.Integer(), nullable=False),
        sa.Column(
            "your_pokemon_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "opponent_pokemon_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["battle_id"],
            ["battle.battle_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "messagelog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("battle_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("frame_number", sa.Integer(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["battle_id"],
            ["battle.battle_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "selectedmove",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("battle_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("frame_number", sa.Integer(), nullable=False),
        sa.Column(
            "your_pokemon_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "opponent_pokemon_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("move", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["battle_id"],
            ["battle.battle_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("selectedmove")
    op.drop_table("messagelog")
    op.drop_table("inbattlepokemonlog")
    op.drop_table("battlesummary")
    op.drop_table("battlepokemonteam")
    op.drop_index(op.f("ix_battle_battle_id"), table_name="battle")
    op.drop_table("battle")
    op.drop_index(op.f("ix_trainer_identity"), table_name="trainer")
    op.drop_table("trainer")
    op.drop_index(op.f("ix_season_season"), table_name="season")
    op.drop_table("season")
    op.drop_table("faintedlog")
    op.drop_table("battlevideo")
    # ### end Alembic commands ###
