"""Fix BattleVideo foreign key relationship

Revision ID: 802ebed3492d
Revises: 4e15a8bdbaf2
Create Date: 2025-09-09 05:36:15.565894

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "802ebed3492d"
down_revision: Union[str, Sequence[str], None] = "4e15a8bdbaf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "battlevideo", "trainer", ["trainer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "battlevideo", type_="foreignkey")
    # ### end Alembic commands ###
