name: Lint and Test For Server

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  lint_and_test_python:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: setup
        run: pip install poetry && poetry install --with dev
      - name: lint
        run: make lint
      - name: build test
        run: make init-docker-server
