name: Lint and Test for Job

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  lint_and_test_python:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - name: lint
        run: make lint
      - name: build test
        run: make init-docker-job
      - name: test-in-docker
        run: make test-in-docker-job
