name: Lint and Test For Server

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  lint_and_test_python:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - name: build test
        run: make init-docker-server
      - name: lint-in-docker
        run: make lint-in-docker
